-- Create the user.
DROP USER calvinLW CASCADE;
CREATE USER calvinLW
	IDENTIFIED BY kec32password
	QUOTA 5M ON System;
GRANT 
	CONNECT,
	CREATE TABLE,
	CREATE SESSION,
	CREATE SEQUENCE,
	CREATE VIEW,
	CREATE MATERIALIZED VIEW,
	CREATE PROCEDURE,
	CREATE TRIGGER,
	UNLIMITED TABLESPACE
	TO calvinLW;

DROP DIRECTORY exp_dir;
CREATE DIRECTORY exp_dir AS 'C:\Users\kec32\Documents\project';
GRANT READ, WRITE ON DIRECTORY exp_dir to calvinLW;